CREATE TABLE Datatable(
    id INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(40),
    email VARCHAR(40),
    phone VARCHAR(25),
    location VARCHAR(40),
    RegistrationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);